Working
BSGreaves/dynamiccards pull request #1
Opened 2017-03-01 01:35 UTC by BSGreaves

@drdreed

Dynamic Cards ready for feedback

2017-03-04 15:17 UTC, drdreed commented on index.html
> +	    	<h1>Dynamic Cards</h1>
Some weird indents here.  Not a big deal just readability.

2017-03-04 15:17 UTC, DevDreed requested changes
Fix up index.html formatting.

2017-03-17 20:10 UTC, BSGreaves commented
@drdreed fixed indents, readme complete, thx.

2017-03-19 01:06 UTC, DevDreed approved these changes
👍

2017-03-20 20:50 UTC, merged